
ZMQLIB=../../slsReceiverSoftware/include
INCDIR= -I$(ZMQLIB)  -I. -I../dataStructures ../tiffIO.cpp -I../ -I../interpolations/
LDFLAG= -L/usr/lib64/ -lpthread -lm  -lstdc++  -lzmq -pthread -lrt -ltiff -L$(ZMQLIB)  -O3 
#-L../../bin -lhdf5  -L.

#DESTDIR?=../bin

all:  moenchZmqProcess

moenchZmqProcess:  moenchZmqProcess.cpp   clean
		      g++ -o moenchZmqProcess  moenchZmqProcess.cpp  $(LDFLAG) $(INCDIR) $(LIBHDF5) $(LIBRARYCBF)  -DNEWZMQ -DINTERP

clean: 	
	rm -f  moenchZmqProcess  


