sudo: false

language: cpp

matrix:
  include:
    - os: linux
      env: CONDA_PY=3.6

dist: trusty

install:
  - sudo apt-get update
  - ldd --version
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - rm -f miniconda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels slsdetectorgroup
  - conda update conda
  - conda update --all
  - conda install conda-build anaconda-client

  # Useful for debugging any issues with conda
  - conda info -a


  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n test-environment python=$CONDA_PY
  - source activate test-environment
  - conda-build .

script:
 - echo "No test scripts to be run!"


deploy:
  provider: script
  script: find $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64 -name "*.tar.bz2" -exec anaconda -t $CONDA_TOKEN upload --force {} \;
  on:
    all_branches: true
