git branch;
cd slsDetectorSoftware; 
git branch;
cd ../slsReceiverSoftware;
git branch;
cd ../slsDetectorGui;
git branch;
cd ../slsDetectorCalibration;
git branch;
cd ../slsImageReconstruction;
git branch;
cd ..
