#!/usr/bin/env python3
from PyQt5 import QtWidgets
import sys

import pyctbgui as ctb

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    main = ctb.MainWindow()
    main.show()
    app.exec_()
