from .ADC import AdcTab
from .Acquisition import AcquisitionTab
from .DACs import DacTab
from .Pattern import PatternTab
from .Plot import PlotTab
from .PowerSupplies import PowerSuppliesTab
from .Signals import SignalsTab
from .SlowADCs import SlowAdcTab
from .Transceiver import TransceiverTab
