package:
    name: sls_detector
    version: refactor

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - python {{ python }}
        - libpng >=1.6.32,<1.6.35
        - setuptools
        - sls_detector_lib refactor
        - pyzmq
        - pybind11 2.2

    host:
        - python
        - pybind11 2.2 

    run:
        - python
        - numpy
        - sls_detector_lib refactor
        - pyzmq
        - libstdcxx-ng
        - libgcc-ng


test:
      imports:
        - sls_detector



about:
    summary: "Interacting with detectors"
