name: Build on RHEL8

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    container:
      image: gitea.psi.ch/detectors-int/rhel8-detectors-dev
    steps:
      # workaround until actions/checkout@v4 is available for RH8
      # - uses: actions/checkout@v4
      - name: Clone repository
        run: |
          echo Cloning ${{ github.ref_name }}
          git clone https://${{secrets.GITHUB_TOKEN}}@gitea.psi.ch/${{ github.repository }}.git --branch=${{ github.ref_name }} .



      - name: Build library 
        run: |
            mkdir build && cd build
            cmake .. -DAARE_PYTHON_BINDINGS=ON -DAARE_TESTS=ON -DPython_FIND_VIRTUALENV=FIRST
            make -j 2 

      - name: C++ unit tests
        working-directory: ${{gitea.workspace}}/build
        run: ctest