name: Build on local RHEL8

on:
  push:
    branches:
      - developer
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "detectors-software-RH8"
    steps:
      - uses: actions/checkout@v4

      - name: Build library 
        run: |
            mkdir build && cd build
            cmake .. -DSLS_USE_PYTHON=ON
            make -j 2 
            cd ../pyctbgui
            make

      - name: Deploy to NFS update server
        if: gitea.ref == 'refs/heads/developer'
        run: |
            sftp -r gitea_runner@mpc2935:/slsDetectorSoftware/RH8 <<< $'put build/bin'
            sftp -r gitea_runner@mpc2935:/slsDetectorSoftware/RH8 <<< $'put pyctbgui'