name: Build on RHEL9

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "ubuntu-latest"
    container:
      image: gitea.psi.ch/detectors-int/rhel9-detectors
    steps:
      - uses: actions/checkout@v4


      - name: Build library 
        run: |
            mkdir build && cd build
            cmake .. 
            make -j 2 

