name: Build and Deploy on local RHEL9

on:
  push:
    branches:
      - developer
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "detectors-software-RH9"
    steps:
      - uses: actions/checkout@v4

      - name: Build library 
        run: |
            mkdir build && cd build
            cmake  -DSLS_USE_PYTHON=ON -DPython_EXECUTABLE=/usr/bin/python3.13 -DPython_INCLUDE_DIR=/usr/include/python3.13 -DPython_LIBRARY=/usr/lib64/libpython3.13.so -DSLS_USE_SIMULATOR=ON -DSLS_USE_GUI=ON ..
            make -j 2 
            cd ../pyctbgui
            make

      - name: Deploy to NFS update server
        if: gitea.ref == 'refs/heads/developer'
        run: |
            sftp -r gitea_runner@mpc2935:/slsDetectorSoftware/RH9 <<< $'put build/bin'
            sftp -r gitea_runner@mpc2935:/slsDetectorSoftware/RH9 <<< $'put pyctbgui'
            sftp -r gitea_runner@mpc2935:/slsDetectorSoftware/RH9 <<< $'put slsDetectorServers/ctbDetectorServer/bin/ctbDetectorServer_developer'