python:
    # - 3.8
    # - 3.9
    # - 3.10
    # - 3.11 
    # - 3.12
    - 3.13

c_compiler_version: # [unix]
  - 11 # [linux]

cxx_compiler_version:
  - 11 # [linux]

c_stdlib_version:              # [linux]
  - 2.17                       # [linux]
