
package:
  name: sls_detector_software
  version: "9.0.0"
  #version: "{{ VERSION_FROM_FILE }}"

source:
  path: ..
  include:
    - VERSION

build:
  number: 0
  binary_relocation: True
  rpaths: 
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    - qt 5.*
    - xorg-libx11
    - xorg-libice
    - xorg-libxext
    - xorg-libsm
    - xorg-libxau
    - xorg-libxrender
    - xorg-libxfixes
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - expat

  host:
    - libstdcxx-ng
    - libgcc-ng
    - xorg-libx11
    - xorg-libice
    - xorg-libxext
    - xorg-libsm
    - xorg-libxau
    - xorg-libxrender
    - xorg-libxfixes
    - expat

  run:
    - libstdcxx-ng
    - libgcc-ng 


outputs:
  - name: slsdetlib
    script: copy_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - libstdcxx-ng
        - libgcc-ng


      run: 
        - libstdcxx-ng
        - libgcc-ng

  - name: slsdet

    script: build_pylib.sh

    requirements:
      build:
        - python
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - setuptools
        - pybind11=2.11

      host:
        - python
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - pybind11=2.11


      run:
        - libstdcxx-ng
        - libgcc-ng
        - python
        - numpy
        - {{ pin_subpackage('slsdetlib', exact=True) }}


    test:
      imports:
        - slsdet

  - name: slsdetgui
    script: copy_gui.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}

      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - qt 5.*
        - expat

  - name: moenchzmq
    script: copy_moench.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}


      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - expat
