package:
  name: sls_detector_software
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}


source:
  path: ..

build:
  number: 0
  binary_relocation: True
  rpaths: 
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{stdlib('c')}}
    - {{compiler('cxx')}}
    - cmake<=3.28
    - ninja
    - qt 5.*

  host:
    - libstdcxx-ng
    - libgcc-ng
    - libgl-devel
    - libtiff
    - zlib
    - expat
  
  run:
    - libstdcxx-ng
    - libgcc-ng 


outputs:
  - name: slsdetlib
    script: copy_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - libstdcxx-ng
        - libgcc-ng

      run: 
        - libstdcxx-ng
        - libgcc-ng

  - name: slsdet
    script: 
      - unset CMAKE_GENERATOR && {{ PYTHON }} -m pip install . -vv  # [not win]

    requirements:
      build:
        - python {{python}}
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        # - {{ pin_subpackage('slsdetlib', exact=True) }} #discuss keeping pinning for simplicity?
        - pybind11>=2.13

      host:
        - cmake
        - ninja
        - python {{python}}
        - pip
        - setuptools
        - pybind11>=2.13
        - scikit-build-core


      run:
        - libstdcxx-ng
        - libgcc-ng
        - python {{python}}


    test:
      imports:
        - slsdet


  - name: slsdetgui
    script: copy_gui.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        

      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - qt 5.*
        - expat

  - name: moenchzmq
    script: copy_moench.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}


      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - expat

