package:
  name: sls_detector_software
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}


source:
  path: ..

build:
  number: 0
  binary_relocation: True
  rpaths: 
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake<=3.28
    - ninja
    - qt 5.*

  host:
    # - libstdcxx-ng
    # - libgcc-ng
    - xorg-libx11
    - xorg-libice
    - xorg-libxext
    - xorg-libsm
    - xorg-libxau
    - xorg-libxrender
    - xorg-libxfixes
    - expat
    - libtiff
    - libpng

  run:
    # - libstdcxx-ng
    # - libgcc-ng 


outputs:
  - name: slsdetlib
    script: copy_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        # - libstdcxx-ng
        # - libgcc-ng

      run: 
        # - libstdcxx-ng
        # - libgcc-ng

  # - name: slsdet
  #   script: build_pylib.sh

  #   requirements:
  #     build:
  #       - python
  #       - {{ compiler('c') }}
  #       - {{compiler('cxx')}}
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}
  #       - setuptools
  #       - pybind11=2.13

  #     host:
  #       - python
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}
  #       - setuptools
  #       - pybind11=2.13


  #     run:
  #       - libstdcxx-ng
  #       - libgcc-ng
  #       - python
  #       - numpy
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}

  #   test:
  #     imports:
  #       - slsdet


  # - name: slsdetgui
  #   script: copy_gui.sh
  #   requirements:

  #     build:
  #       - {{ compiler('c') }}
  #       - {{compiler('cxx')}}
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}

  #     run:
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}
  #       - qt 5.*
  #       - expat

  # - name: moenchzmq
  #   script: copy_moench.sh
  #   requirements:

  #     build:
  #       - {{ compiler('c') }}
  #       - {{compiler('cxx')}}
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}


  #     run:
  #       - {{ pin_subpackage('slsdetlib', exact=True) }}
  #       - expat
