# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/google/yapf
  rev: v0.40.1
  hooks:
    - id: yapf
      name: yapf
      language: python
      entry: yapf
      args: [-i,--style,pyproject.toml]
      types: [python]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.0.285
  hooks:
    - id: ruff
