
DESTDIR ?= ./

CC    = gcc
CFLAGS += -Wall  -DGOTTHARDD -DMCB_FUNCS -DDACS_INT  -DDEBUG -DVIRTUAL 


PROGS= 		$(DESTDIR)/gotthardDetectorServer_virtual 


SRCS = server.c server_funcs.c communication_funcs.c firmware_funcs.c mcb_funcs.c 
OBJS = $(SRCS:%.c=%.o) 

gotthardVirtualServer = $(PROGS)

all:	clean $(PROGS) 


$(PROGS): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $^ $(LDLIBS_$@) $(LDFLAGS_$@)


clean:
	rm -rf $(PROGS)  *.o *.gdb






