/********************************************************************
* TSlsDetectorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TSlsDetectorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#include "cint/G__ci.h"
extern "C" {
extern void G__cpp_setup_tagtableTSlsDetectorDict();
extern void G__cpp_setup_inheritanceTSlsDetectorDict();
extern void G__cpp_setup_typetableTSlsDetectorDict();
extern void G__cpp_setup_memvarTSlsDetectorDict();
extern void G__cpp_setup_globalTSlsDetectorDict();
extern void G__cpp_setup_memfuncTSlsDetectorDict();
extern void G__cpp_setup_funcTSlsDetectorDict();
extern void G__set_cpp_environmentTSlsDetectorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "energyCalibration.h"
#include "angularCalibration.h"

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSlsDetectorDictLN_energyCalibrationFunctions;
extern G__linked_taginfo G__TSlsDetectorDictLN_energyCalibration;
extern G__linked_taginfo G__TSlsDetectorDictLN_angularCalibration;

/* STUB derived class for protected member access */
