package:
  name: sls_detector_software
  version: 2025.3.19


source:
  path: ../..

build:
  number: 0
  binary_relocation: True
  rpaths: 
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    
    - cmake
    - ninja
    - qt 5.*
    # - xorg-libx11
    # - xorg-libice
    # - xorg-libxext
    # - xorg-libsm
    # - xorg-libxau
    # - xorg-libxrender
    # - xorg-libxfixes
    # - {{ cdt('mesa-libgl-devel') }}      # [linux]
    # - {{ cdt('mesa-libegl-devel') }}     # [linux]
    # - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # - {{ cdt('libselinux') }}            # [linux]
    # - {{ cdt('libxdamage') }}            # [linux]
    # - {{ cdt('libxxf86vm') }}            # [linux]
    # - expat

  host:
    - libstdcxx-ng
    - libgcc-ng
    - libgl-devel  # [linux]
    # - xorg-libx11
    # - xorg-libice
    # - xorg-libxext
    # - xorg-libsm
    # - xorg-libxau
    # - xorg-libxrender
    # - xorg-libxfixes
    # - expat
    - libtiff
    # - libpng

  run:
    # - libstdcxx-ng
    # - libgcc-ng 


outputs:
  - name: slsdetlib
    script: copy_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        # - libstdcxx-ng
        # - libgcc-ng

      run: 
        # - libstdcxx-ng
        # - libgcc-ng




  - name: slsdetgui
    script: copy_gui.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}

      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - qt 5.*
        - expat

  - name: moenchzmq
    script: copy_moench.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}


      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - expat