#{% set version = load_file('VERSION').strip %}
package:
  name: sls_detector_software
  version: {{ environ.get('VERSION') }} #2025.3.19
  
source:
  path: ../..

build:
  number: 0
  binary_relocation: True
  rpaths: 
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - git
    - cmake<=3.28
    - ninja
    - qt 5.*

  host:
    - libstdcxx-ng
    - libgcc-ng
    - libgl-devel  # [linux]
    - libtiff
    - zlib
    - expat

  run:
    - libstdcxx-ng
    - libgcc-ng 


outputs:
  - name: slsdetlib
    script: copy_lib.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}

      run: 
        - libstdcxx-ng
        - libgcc-ng




  - name: slsdetgui
    script: copy_gui.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}

      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
        - qt 5.*


  - name: moenchzmq
    script: copy_moench.sh
    requirements:

      build:
        - {{ compiler('c') }}
        - {{compiler('cxx')}}
        - {{ pin_subpackage('slsdetlib', exact=True) }}


      run:
        - {{ pin_subpackage('slsdetlib', exact=True) }}
