python:
    # - 3.8
    # - 3.9
    # - 3.10
    # - 3.11 
    # - 3.12
    - 3.13

c_compiler:
  - gcc                        # [linux]

c_compiler_version: 
  - 13 # [linux]

c_stdlib:
  - sysroot                    # [linux]

cxx_compiler:
  - gxx                        # [linux]


cxx_compiler_version:
  - 13 # [linux]

c_stdlib_version:              # [linux]
  - 2.17                       # [linux]