FIND_PATH (CBF_INCLUDE_DIR
    ${CBF_DIR}/include
    ${CBF_DIR}/include/cbflib
)
FIND_LIBRARY (CBF_LIBRARY
    NAMES cbf
    HINTS ${CBF_DIR}/lib
)
INCLUDE ( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS (CBF DEFAULT_MSG CBF_LIBRARY CBF_INCLUDE_DIR )

