name: Build inplace, run tests and linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build C extension
        run: |
          make
      - name: Run tests using pytest
        run: |
          make test
      - name: check code formatting
        run: |
          make check_format
      - name: lint the code with ruff
        run: |
           make lint