name: Run Simulator Tests

on:
  push:



env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
      - run: pip install pytest numpy colorama

      # using a stable action version instead of latest to create/restore cache for now
      - uses: awalsh128/cache-apt-pkgs-action@v1.6.1
        with:
          packages: libhdf5-dev 
          version: 1.0

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
          -DSLS_USE_TESTS=ON \
          -DSLS_USE_SIMULATOR=ON \
          -DSLS_USE_PYTHON=ON \
          -DSLS_USE_HDF5=ON

      - name: Build
          # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build -j4 --config ${{env.BUILD_TYPE}}

      - name: Simulator unit tests
        working-directory: ${{github.workspace}}/build/bin
        run: |
          python test_simulators.py --no-log-file --quiet --tests "[detectorintegration]~[disable_check_data_file]"
          #remove --quiet to see more prints from simulator, receiver and tests
          python test_frame_synchronizer.py
        

      - name: Python unit tests with simulators
        working-directory: ${{github.workspace}}/build/bin
        run: |
          python -m pytest -m detectorintegration ${{github.workspace}}/python/tests --detector-integration 
          python -m pytest ${{github.workspace}}/python/tests

      - name: C++ unit tests
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -j1 --rerun-failed --output-on-failure
